# Generated by Django 4.2.2 on 2023-06-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('PC_id', models.IntegerField(primary_key=True, serialize=False)),
                ('PC_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_id', models.IntegerField()),
                ('P_name', models.CharField(max_length=100)),
                ('P_price', models.IntegerField()),
                ('P_description', models.CharField(max_length=100)),
                ('P_date', models.DateField()),
                ('PC_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_category')),
            ],
        ),
    ]
